FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY src/pipeline/tracker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/pipeline/tracker/ .
CMD ["python", "main.py"]
