FROM nvidia/cuda:12.2.0-base-ubuntu22.04

RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY src/pipeline/detector/requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY src/pipeline/detector/ .
CMD ["python3", "main.py"]
